# Generated by Django 4.2.7 on 2023-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('tx_hash', models.TextField(max_length=255)),
                ('media_url', models.TextField(null=True)),
                ('owner', models.TextField(null=True)),
            ],
        ),
    ]
